apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: dir
        persistentVolumeClaim:
          claimName: dir
      containers:
      - name: php
        image: php:7-fpm
        volumeMounts:
        - name: dir
          mountPath: /dir
      initContainers:
      - name: cleandir
        image: busybox
        volumeMounts:
        - name: dir
          mountPath: /dir
        command: ['sh', '-c', "rm -frv /dir/k8s-gcp-php-nginx && rm -frv /dir/html"]      
      - name: git-cloner
        image: alpine/git
        args:
            - clone
            - --single-branch
            - --
            - https://github.com/james-ransom/k8s-gcp-php-nginx.git
            - /dir/k8s-gcp-php-nginx
        volumeMounts:
        - mountPath: /dir
          name: dir
      - name: installcode
        image: busybox
        volumeMounts:
        - name: dir
          mountPath: /dir
        command: ['sh', '-c', "mkdir -p /dir/html && cp -v /dir/k8s-gcp-php-nginx/*.php /dir/html/"]    